//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PikitikosCE
{
    using System;
    using System.Collections.Generic;
    
    public partial class credito
    {
        public int idCredito { get; set; }
        public Nullable<float> Cantidad { get; set; }
        public int IdPersona { get; set; }
        public sbyte Tiene { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
