//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PikitikosCE
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagoscredito
    {
        public int idPagosCredito { get; set; }
        public int idPersona { get; set; }
        public float CreditoActual { get; set; }
        public float Pago { get; set; }
        public System.DateTime FechaDePago { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
