//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PikitikosCE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pikitikosdbEntities : DbContext
    {
        public pikitikosdbEntities()
            : base("name=pikitikosdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articulo> articuloes { get; set; }
        public virtual DbSet<caracteristica> caracteristicas { get; set; }
        public virtual DbSet<color> colors { get; set; }
        public virtual DbSet<credito> creditoes { get; set; }
        public virtual DbSet<inventario> inventarios { get; set; }
        public virtual DbSet<pagoscredito> pagoscreditoes { get; set; }
        public virtual DbSet<persona> personas { get; set; }
        public virtual DbSet<talla> tallas { get; set; }
        public virtual DbSet<tipoarticulo> tipoarticuloes { get; set; }
        public virtual DbSet<tipotela> tipotelas { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
    }
}
